# Generated by Django 3.1.5 on 2021-01-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
