# Generated by Django 3.1.4 on 2020-12-20 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activations_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activations_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 11, 16, 37, 466692, tzinfo=utc)),
        ),
    ]
