# Generated by Django 3.1.4 on 2021-01-06 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210105_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activations_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 10, 8, 15, 255826, tzinfo=utc)),
        ),
    ]
