# Generated by Django 3.1.5 on 2021-01-20 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210106_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activations_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 40, 48, 913991, tzinfo=utc)),
        ),
    ]
